apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    version: v1
  name: frontend
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
    version: v1
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      serviceAccountName: frontend
      containers:
        - env:
            - name: "UPSTREAM_URIS"
              value: "http://backend.global"
            - name: SERVICE_OWNER
              value: "dave"
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:8080"
            - name: "SERVER_TYPE"
              value: "http"
            - name: "NAME"
              value: "frontend-cluster1"
            - name: "MESSAGE"
              value: "Hello from frontend"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: rinormaloku/happy-service:latest
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            privileged: false
